### ISSUE TITLE
why retreive the first element of action

### ISSUE THREAD

**Issue by cometta** [xuanlinli17/CS285_Fa19_Deep_Reinforcement_Learning#9]
https://github.com/xuanlinli17/CS285_Fa19_Deep_Reinforcement_Learning/blob/ba2e8e18c60b3a074f735d045b40f04a20efffca/hw1/cs285/infrastructure/utils.py#L32

May i know why, this statement only return the first element, instead of using argmax to choose the best action, output from tf.multinomial?

**Comment by xuanlinli17** [comment]
I think you can print out the shape of `ac`  before this statement is reached. Also the environment is continuous for hw1.
